### ISSUE TITLE
Contributed Parent interfaces on MergedSubcomponents are getting double added to the parent component

### ISSUE THREAD

**Issue by r0adkll** [ZacSweers/anvil#51]
If you have the following subcomponent setup (either hand crafted or generated) Anvil will merge both the contributed `Parent` interface and the subclassed `ParentComponent` interface in the generated `Merged*` component:

```kotlin
@SingleIn(FeatureScope::class)
@MergeSubcomponent(FeatureScope::class)
interface FeedComponent {

  fun inject(screen: FeedScreen)

  @ContributesTo(UserScope::class)
  interface Parent {
    val feedComponentFactory: Factory
  }

  @MergeSubcomponent.Factory
  interface Factory {
    fun create(
      @BindsInstance activityContext: Context,
    ): FeedComponent
  }
}
```

will result in a merged parent component like so

```kotlin
//…
@Subcomponent(modules = […])
public interface MergedUserComponent : UserComponent,
  FeedComponent.Parent, MergedFeedComponent.ParentComponent, … {
```

This leads to a supertype overflow in Kotlin where it has a hard limit @ 1000 supertypes per class.

Repro Project: https://github.com/r0adkll/anvil-ic-bug-repro

**Comment by ZacSweers** [comment]
I think it's not possible to avoid this by only adding one parent component because it will still incur its parent as another super type.

That said, I talked to the kotlin compilers team and they're going to remove this limitation in 2.1.0, so shouldn't be an issue that release. https://youtrack.jetbrains.com/issue/KT-49235

Open to revisiting if you think this can be avoided sooner though, lmk
